In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression

In [23]:
data = pd.read_csv("datasets/diabetes.csv")
data.head(7)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
5,5,116,74,0,0,25.6,0.201,30,0
6,3,78,50,32,88,31.0,0.248,26,1

In [19]:
data.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [25]:
data = data.iloc[:, :8].replace(0, np.nan)

In [14]:
data.head(20)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6.0,148.0,72.0,35.0,NaN,33.6,0.627,50
1,1.0,85.0,66.0,29.0,NaN,26.6,0.351,31
2,8.0,183.0,64.0,NaN,NaN,23.3,0.672,32
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21
4,NaN,137.0,40.0,35.0,168.0,43.1,2.288,33
5,5.0,116.0,74.0,NaN,NaN,25.6,0.201,30
6,3.0,78.0,50.0,32.0,88.0,31.0,0.248,26
7,10.0,115.0,NaN,NaN,NaN,35.3,0.134,29
8,2.0,197.0,70.0,45.0,543.0,30.5,0.158,53
9,8.0,125.0,96.0,NaN,NaN,NaN,0.232,54
10,4.0,110.0,92.0,NaN,NaN,37.6,0.191,30
11,10.0,168.0,74.0,NaN,NaN,38.0,0.537,34
12,10.0,139.0,80.0,NaN,NaN,27.1,1.441,57
13,1.0,189.0,60.0,23.0,846.0,30.1,0.398,59
14,5.0,166.0,72.0,19.0,175.0,25.8,0.587,51
15,7.0,100.0,NaN,NaN,NaN,30.0,0.484,32
16,NaN,118.0,84.0,47.0,230.0,45.8,0.551,31
17,7.0,107.0,74.0,NaN,NaN,29.6,0.254,31
18,1.0,103.0,30.0,38.0,83.0,43.3,0.183,33
19,1.0,115.0,70.0,30.0,96.0,34.6,0.529,32

In [26]:
data.isna().sum()

Pregnancies                 111
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
dtype: int64